import path from "path";
import { fileURLToPath } from "url";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import { viteSingleFile } from "vite-plugin-singlefile";
import { readdirSync, writeFileSync } from "fs";
import { join } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function manifestPlugin() {
  const generate = () => {
    try {
      const dataDir = join(__dirname, 'public', 'data');
      const manifestPath = join(dataDir, 'file-manifest.json');
      const files = readdirSync(dataDir)
        .filter(f => f.endsWith('.json') && f !== 'file-manifest.json')
        .sort((a, b) => {
          const parseDate = (f: string) => {
            const parts = f.replace('.json', '').split('-');
            if (parts.length === 3) {
              return new Date(Number(parts[2]), Number(parts[1]) - 1, Number(parts[0])).getTime();
            }
            return 0;
          };
          return parseDate(b) - parseDate(a); // Sort descending to have latest date first
        });
      const manifest = {
        files,
        generatedAt: new Date().toISOString(),
        autoGenerated: true
      };
      writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
      console.log(`[manifest-plugin] Generated manifest with ${files.length} files.`);
    } catch (err: any) {
      console.error('[manifest-plugin] Failed:', err.message);
    }
  };

  return {
    name: 'manifest-plugin',
    buildStart() {
      generate();
    },
    configureServer(server: any) {
      server.watcher.on('add', (filePath: string) => {
        if (filePath.includes('public' + path.sep + 'data') && filePath.endsWith('.json')) {
          generate();
        }
      });
      server.watcher.on('unlink', (filePath: string) => {
        if (filePath.includes('public' + path.sep + 'data') && filePath.endsWith('.json')) {
          generate();
        }
      });
    }
  };
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), tailwindcss(), viteSingleFile(), manifestPlugin()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
    },
  },
});
